# Generated by Django 5.2.5 on 2025-11-09 03:34

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tanu', '0002_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
